### ISSUE TITLE
Integration cmake <-> qmake

### ISSUE THREAD

**Issue by zwostein** [Robotregent/EBP#1]
Da ihr so gerne den QtCreator verwendet ;) :
Wenn das Ding nicht direkt cmake unterstützt, könnte man versuchen dem qmake die eine oder andere Regel beizubringen um  cmake aufzurufen. So, dass qmake automatisch die Bibliothek als Abhängigkeit baut.

**Comment by Robotregent** [comment]
Schau ich mir mal an. Dann versuch ich auch gleich das Aktualisieren der DB zu automatisieren.
