### ISSUE TITLE
Funktionen für Betreuungsdokumentation 

### ISSUE THREAD

**Issue by Robotregent** [Robotregent/EBP#13]
Template für eine Tabelle der Betreuungsdokumentation:
- Tabellenname
- Kurzbeschreibung
- Einstufung
  - Ich benötige keine Hilfe
  - Ich bekomme Beratung
  - Ich bekomme Assistenz
  - Das machen Mitarbeiter für mich
  - Das ist mir besonders wichtig
  - Das will ich lernen
- Erläuterungen
- Aktuelle Ziele

Folgende sechs Tabellen sollen implementiert werden:
- Einkaufen
- Wäschepflege
- Körperpflege
- Aufstehen / zu Bett gehen
- In Partnerschaften
- In Freundschaften

**Comment by zwostein** [comment]
Eine etwas vereinfachte Version ist implementiert - wird sich bei Bedarf dann ändern ;)
