### ISSUE TITLE
Berechtigungen

### ISSUE THREAD

**Issue by zwostein** [Robotregent/EBP#33]
Um das Rechtesystem umzusetzen müsste ich noch genau wissen auf welche Tabellen/Objekte/Methoden der jeweilige Benutzer zugreifen darf. "AdminRecht" ist klar, "WohnverbundRecht", "WohnheimRecht" und "WohngruppenRecht" eher weniger.

**Comment by Robotregent** [comment]
Schau mal nochmal ins Pflichtenheft. Ich glaube es gibt nur noch "AdminRecht"  und "WohngruppenRecht". 
Das heißt, dass jeder Mitarbeiter nur die Wohngruppen bearbeiten/lesen darf, mit denen er veknüpft ist. Und nur Bewohner bearbeiten/lesen darf, die auf solch verknüpften Wohngruppen wohnen. 

Das regelt sich dann auch schon von allein im Client, da der Ausgangspunkt für das Laden der Daten der eingeloggte Mitarbeiter ist und nur seine Wohngruppen geladen werden, bzw die Bewohner dieser Wohngruppen.

Aber schau doch nochmal ins abgegebene Pflichtenheft. Nicht, dass ich das fehlinterpretier...
