### ISSUE TITLE
Meldeliste

### ISSUE THREAD

**Issue by Robotregent** [Robotregent/EBP#34]
Wir haben im Pflichtenheft noch sowas wie ne Meldeliste^^.  Keine Ahnung, wie wir das vernünftig Implementieren können.

**Comment by Robotregent** [comment]
Wie besprochen, mit ner Abwesenheitstabelle..

**Comment by zwostein** [comment]
Implementiert!
Nicht vergessen die SQL Datenbank neu zu initialisieren ;)
