### ISSUE TITLE
QS linkProjekt

### ISSUE THREAD

**Issue by Robotregent** [Robotregent/EBP#41]
In doxygen steht noch:

Bewohner::linkProjekt(bewohner,projekt)

geht aber nur noch andersrum.

Weiß nicht ob das Absicht wegen Eindeutigkeit ist (dann bitte aus doxygen löschen) oder ein Fehler ist.

**Comment by Robotregent** [comment]
Das gleiche gilt für Bewohner::linkProtokoll(protokoll,bewohner)

**Comment by zwostein** [comment]
Danke!
Hatte das falsche Makro verwendet:
In der Klasse Bewohner waren mehrere link-Methoden nicht als inverses Gegenstück deklariert.
Die "inversen" Links werden normalerweise aus der Klasse rausgenommen - es sei denn "DATABASEOBJECT_ENABLE_INVERSE" wird definiert - dann kann man wieder von beiden Seiten linken.

**Comment by Robotregent** [comment]
Verrückte Welt :)
