### ISSUE TITLE
Lib - Betreuung

### ISSUE THREAD

**Issue by Robotregent** [Robotregent/EBP#44]
Felder: 
- Verein - String
- Vorname - String
- Nachname - String
- Straße - String
- PLZ - String
- Ort - String
- Telefon - String
- Fax - String
- E-Mail - String
- Gesundheitsfürsorge - bool
- Vermögensfürsorge - bool
- Aufenthaltsbestimmung - bool

**Comment by zwostein** [comment]
implementiert

**Comment by Robotregent** [comment]
Das Feld Verein (oder auch Organisation) fehlt noch.

**Comment by Robotregent** [comment]
Danke.
