### ISSUE TITLE
Fehlerticket

### ISSUE THREAD

**Issue by Robotregent** [Robotregent/EBP#51]
Ich hab hier nen Fehler, den ich durch die Tests nicht nachbilden kann.
Wenn ich neue Mitarbeiter anlege(Im AdminDialog), und die dann benutzen will (Nach dem Einloggen im Client beim Laden der Bewohner oder Wohngruppe) kommt folgende Exception:
terminate called after throwing an instance of 'odb::already_in_transaction'
  what():  transaction already in progress in this thread

Kannst du dir das anschauen? Ich versuch das derweil in nem Test nachzubilden.

**Comment by zwostein** [comment]
zugriff aus verschiedenen threads? anders kann ich mir das im augenblick nicht erklären

**Comment by zwostein** [comment]
fixed ;)
