### ISSUE TITLE
Bewohner::hasPermission

### ISSUE THREAD

**Issue by Robotregent** [Robotregent/EBP#52]
Wie soll hasPermission funktionieren?

Ideal wäre, wenn geprüft wird, ob der Mitarbeiter der Connection die Bezugsbetreuung für den Bewohner hat :) 

Ist das so, oder bezieht es sich auf was anderes?

**Comment by zwostein** [comment]
hasPermissions wird intern verwendet - aber so in etwa funktioniert es.
Getestet hab ich es nicht wirklich, aber die load-Funktionen sollten nur Daten zurückgeben auf die der verwendete Mitarbeiter Zugriff hat.

**Comment by Robotregent** [comment]
Ok. Danke.
