### ISSUE TITLE
Screencast

### ISSUE THREAD

**Issue by Robotregent** [Robotregent/EBP#53]
Für die Thinking-Aloud-Tests such ich noch nach ner vernünftigen Software, um die Screencasts aufzunehmen. Hab schon folgendes versucht:
- Instabul. Läuft bei mir nicht. Wohl zu alt ^^^
- vlc. Frisst den gesammten Speicher auf und hängt dann.
- recordmydesktop. Sah am vielversprechendsten aus. Schneidet aber die Fenster beim Aufnehmen zur hälfte ab. Hab die fps auf 45 hoch gesetzt und noch so ne Einstellung getätigt, die recordmydesktop ganze Screenshots zur Aufnahme nutzt, nicht nur die Differenz. Bringt aber alles nix.

Hat einer von euch da Erfahrung? Bzw könnt ihr mal schauen, ob recordmydesktop bei euch sauber aufnimmt? Vlt. liegt es an meiner popligen Netbook Grafikkarte und den schlechten ati Treiber...

**Comment by Robotregent** [comment]
Ok laut http://wiki.ubuntuusers.de/screencasts ist an allem unity schuld.

Ich versuch es heute Abend mal mit FFmpeg. Scheint mir am aussichtsreichsten ...

**Comment by CriVe-** [comment]
Ein Kumpel von mir schwört auf Freeseer (https://github.com/Freeseer/freeseer/wiki), aber habs selbst nicht getestet, und es gab zumindest letztes Jahr wohl auch Ubuntu Probleme - keine Ahnung ob das jetzt schon wieder besser ist.
